services:
  server:
    image: dash/coinflip
    ports:
      - "3000:3000"
    volumes:
      - coinflip-server:/app/data
      - ${PWD}/server-config.yml:/app/config.yml
    container_name: coinflip_server
    depends_on:
      - dash
    links:
        - "dash:dash"
  dash:
    image: dashpay/dashd:0.17.0.0-rc4-hotfix2
    hostname: dash
    ports:
      - "19998-19999:19998-19999"
      - "28332:28332"
    container_name: coinflip_dash
    entrypoint: dashd
    volumes:
      - coinflip-dash:/dash
      - ${PWD}/dash.conf:/dash/.dashcore/dash.conf
volumes:
  coinflip-server: {}
  coinflip-dash: {}
