services:
  server:
    image: dash/coinflip
    ports:
      - "3330:3330"
    volumes:
      - coinflip-server:/app/data
      - ${PWD}/server-config.yml:/app/config.yml
    container_name: coinflip_server
    depends_on:
      - dash
    links:
        - "dash:dash"
  dash:
    image: dashpay/dashd:latest
    hostname: dash
    ports:
      - "19999:19999"
      - "127.0.0.1:19998:19998"
      - "28333:28333"
    container_name: coinflip_dash
    entrypoint: dashd
    volumes:
      - coinflip-dash:/home/dash/.dashcore
      - ${PWD}/dash.conf:/home/dash/.dashcore/dash.conf
volumes:
  coinflip-server: {}
  coinflip-dash: {}
